spring:
  config:
    activate.on-profile: test
  application:
    name: ShareItAppTest
  main:
    banner-mode: OFF
  datasource:
    username: dbuser
    password: 12345
    url: jdbc:h2:mem:shareit;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always